<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/pallet.glb
Author: Andrea Spognetta (Spogna) (https://sketchfab.com/spogna)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/eur-pallet-rawscan-f318b6e1cceb4473a1c35dc9196fd1a4
Title: EUR Pallet  .::RAWscan::.
-->

<script>
	import { T } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const gltf = useGltf('/static/pallet.glb');
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group rotation={[-Math.PI, 0, 0]}>
			<T.Mesh geometry={gltf.nodes.Object_2.geometry} material={gltf.materials.material_0} />
			<T.Mesh geometry={gltf.nodes.Object_3.geometry} material={gltf.materials.material_0} />
			<T.Mesh geometry={gltf.nodes.Object_4.geometry} material={gltf.materials.material_0} />
			<T.Mesh geometry={gltf.nodes.Object_5.geometry} material={gltf.materials.material_0} />
			<T.Mesh geometry={gltf.nodes.Object_6.geometry} material={gltf.materials.material_0} />
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
